### ISSUE TITLE
Android app/build.gradle mods broken

### ISSUE THREAD

**Issue by shamilovtim** [microsoft/react-native-test-app#2259]
### What happened?

A functioning Expo Android config plugin with mods to app/build.gradle does not work with react native test app. It seems react native test app does not symlink a real `app/build.gradle` and instead hides it away in the node_modules folder. I think this is a problem but I'm not sure what the solution is.

### Version

3.10.9

### What platforms are you seeing this issue on?

- [X] Android
- [ ] iOS
- [ ] macOS
- [ ] visionOS
- [ ] Windows

### System Information

```true
System:
  OS: macOS 14.4.1
  CPU: (10) arm64 Apple M1 Max
  Memory: 11.58 GB / 64.00 GB
  Shell:
    version: 3.5.1
    path: /usr/local/bin/fish
Binaries:
  Node:
    version: 20.15.1
    path: ~/.nvm/versions/node/v20.15.1/bin/node
  Yarn:
    version: 3.6.1
    path: ~/.nvm/versions/node/v20.15.1/bin/yarn
  npm:
    version: 10.7.0
    path: ~/.nvm/versions/node/v20.15.1/bin/npm
  Watchman:
    version: 2024.08.19.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.15.2
    path: /Users/admin/.rvm/gems/ruby-3.2.2/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.5
      - iOS 17.5
      - macOS 14.5
      - tvOS 17.5
      - visionOS 1.2
      - watchOS 10.5
  Android SDK:
    Android NDK: 22.1.7171670
IDEs:
  Android Studio: 2024.1 AI-241.19072.14.2412.12360217
  Xcode:
    version: 15.4/15F31d
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.12
    path: /opt/homebrew/opt/openjdk@17/bin/javac
  Ruby:
    version: 3.2.2
    path: /Users/admin/.rvm/rubies/ruby-3.2.2/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.3.1
    wanted: 18.3.1
  react-native:
    installed: 0.75.3
    wanted: ^0.75.3
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: false
  newArchEnabled: true
iOS:
  hermesEnabled: false
  newArchEnabled: false
```

### Steps to Reproduce

1. Place an Android config plugin in `example/plugin.js` which modifies settings gradle and app/build.gradle. Source code:

```js
"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
/* eslint-disable @typescript-eslint/no-shadow */
const config_plugins_1 = require("expo/config-plugins");
const package_json_1 = __importDefault(require("../../package.json"));
const withMyPlugin = (config) => {
    /**
     * Modify the app/build.gradle file within an Expo managed project
     * to enable view binding.
     */
    config = (0, config_plugins_1.withAppBuildGradle)(config, async (config) => {
        if (config.modResults.language === 'groovy') {
            // Ensure we don't duplicate the viewBinding block if it's already present
            if (!config.modResults.contents.includes('viewBinding {')) {
                // Find the location of the 'android' block and insert the viewBinding configuration
                const position = config.modResults.contents.indexOf('android {');
                if (position !== -1) {
                    const before = config.modResults.contents.substring(0, position + 'android {'.length);
                    const after = config.modResults.contents.substring(position + 'android {'.length);
                    config.modResults.contents = `${before}
    viewBinding {
        enabled = true
    }
${after}`;
                }
            }
        }
        return config;
    });
    config = (0, config_plugins_1.withSettingsGradle)(config, (config) => {
        config.modResults.contents = applySettingsGradle(config.modResults.contents);
        return config;
    });
    return config;
};
function applySettingsGradle(gradleSettings) {
    const mySettings = `\ninclude ':${package_json_1.default.name}:sdk', ':${package_json_1.default.name}:module'`;
    // Make sure the project does not have the settings already
    if (!gradleSettings.includes(`include :${package_json_1.default.name}:sdk', ':${package_json_1.default.name}:module'`)) {
        return gradleSettings + mySettings;
    }
    return gradleSettings;
}
exports.default = (0, config_plugins_1.createRunOncePlugin)(withMyPlugin, 'plugin.js', package_json_1.default.version);
```

2. run `yarn add @expo/config-plugins` to the /example/ project
3. run `yarn android` in the /example/ project
4. receive error:

```
> Failed to apply config plugins: /example/node_modules/@expo/config-plugins/build/android/Paths.js:107 throw new Error(`Failed to find '${gradleName}.gradle' file for project: ${projectRoot}.`); ^ Error: [android.appBuildGradle]: withAndroidAppBuildGradleBaseMod: Failed to find 'build.gradle' file for project: /example/android/app. at getGradleFilePath (/example/node_modules/@expo/config-plugins/build/android/Paths.js:107:11) at Object.getAppBuildGradleFilePath (/example/node_modules/@expo/config-plugins/build/android/Paths.js:125:10) at getFilePath (/example/node_modules/@expo/config-plugins/build/plugins/withAndroidBaseMods.js:461:31) at action (/example/node_modules/@expo/config-plugins/build/plugins/createBaseMod.js:57:34) at interceptingMod (/example/node_modules/@expo/config-plugins/build/plugins/withMod.js:104:27) at evalModsAsync (/example/node_modules/@expo/config-plugins/build/plugins/mod-compiler.js:206:31) at compileModsAsync (file:///example/node_modules/react-native-test-app/scripts/config-plugins/plugins/mod-compiler.mjs:33:10) at applyConfigPlugins (file:///example/node_modules/react-native-test-app/scripts/config-plugins/apply.mjs:23:10) Node.js v20.15.1 * Try:
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by shamilovtim** [comment]
Update: adding a symlinked build.gradle to `/example/android/app/build.gradle` and pointing at `example/node_modules/react-native-test-app/android/app/build.gradle` works as a temporary fix

**Comment by tido64** [comment]
Can you try patching `node_modules/react-native-test-app/scripts/config-plugins/plugins/withAndroidBaseMods.mjs` locally:

```diff
   ),
   projectBuildGradle: expoProviders.projectBuildGradle,
   settingsGradle: expoProviders.settingsGradle,
-  appBuildGradle: expoProviders.appBuildGradle,
+  appBuildGradle: modifyFilePath(
+    expoProviders.appBuildGradle,
+    "app/build.gradle"
+  ),
   mainActivity: modifyFilePath(
     expoProviders.mainActivity,
     "app/src/main/java/com/microsoft/reacttestapp/MainActivity.kt"
```

I think we just missed a remapping here.

**Comment by shamilovtim** [comment]
Patch works, thank you!

**Comment by shamilovtim** [comment]
Leaving open for tracking purposes
