### ISSUE TITLE
Android: `react-native run-android` fails to build test app

### ISSUE THREAD

**Issue by tido64** [microsoft/react-native-test-app#226]
`react-native run-android` fails to find the Android test app. This can be reproduced in the Example app:

```
$ yarn react-native run-android
error Android project not found. Are you sure this is a React Native project? If your Android files are located in a non
-standard location (e.g. not inside 'android' folder), consider setting `project.android.sourceDir` option to point to a
 new location. Run CLI with --verbose flag for more details.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

This happens even after setting `project.android.sourceDir`:

```diff
$ git diff react-native.config.js
diff --git a/example/react-native.config.js b/example/react-native.config.js
index 69684ba..29998d0 100644
--- a/example/react-native.config.js
+++ b/example/react-native.config.js
@@ -9,6 +9,9 @@ if (process.argv.includes("--config=metro.config.macos.js")) {
 } else {
   module.exports = {
     project: {
+      android: {
+        sourceDir: "android",
+      },
       ios: {
         project: "ios/ReactTestApp-Dummy.xcodeproj",
       },

```

**Comment by tido64** [comment]
In order for `sourceDir` to be picked up, `manifestPath` must also be set. Setting it to the manifest in `react-native-test-app` gives us another error:

```
$ react-native run-android --deviceId A1NGAR1840900211
info Running jetifier to migrate libraries to AndroidX. You can disable it using "--no-jetifier" flag.
(Use `node --trace-warnings ...` to show where the warning was created)
Jetifier found 1948 file(s) to forward-jetify. Using 8 workers...
info JS server already running.
info Building the app...

FAILURE: Build failed with an exception.

* Where:
Script '/~/example/node_modules/react-native-test-app/android/test-app-native-modules.gradle' line: 230

* What went wrong:
A problem occurred evaluating script.
> Calling `[node, /~/example/node_modules/@react-native-community/cli/build/bin.js, config]` finished with an exception. Error message: groovy.json.JsonException: Unable to determine the current character, it is not a string, number, array, or object

  The current character read is 'E' with an int value of 69
  Unable to determine the current character, it is not a string, number, array, or object
  line number 1
  index number 0
  Error: ENOENT: no such file or directory, open '/~/node_modules/react-native-test-app/android/app/src/main/AndroidManifest.xml'    at Object.openSync (fs.js:466:3)    at Object.readFileSync (fs.js:369:35)    at readManifest (/~/example/node_modules/@react-native-community/cli-platform-android/build/config/readManifest.js:38:60)    at Object.projectConfig (/~/example/node_modules/@react-native-community/cli-platform-android/build/config/index.js:70:46)    at Object.get project [as project] (/~/example/node_modules/@react-native-community/cli/build/tools/config/index.js:106:50)    at filterConfig (/~/example/node_modules/@react-native-community/cli/build/commands/config/config.js:13:20)    at Object.func (/~/example/node_modules/@react-native-community/cli/build/commands/config/config.js:27:32)    at Command.handleAction (/~/example/node_modules/@react-native-community/cli/build/index.js:186:23)    at Command.listener (/~/example/node_modules/commander/index.js:315:8)    at Command.emit (events.js:314:20)
  ^. Output: Error: ENOENT: no such file or directory, open '/~/node_modules/react-native-test-app/android/app/src/main/AndroidManifest.xml'    at Object.openSync (fs.js:466:3)    at Object.readFileSync (fs.js:369:35)    at readManifest (/~/example/node_modules/@react-native-community/cli-platform-android/build/config/readManifest.js:38:60)    at Object.projectConfig (/~/example/node_modules/@react-native-community/cli-platform-android/build/config/index.js:70:46)    at Object.get project [as project] (/~/example/node_modules/@react-native-community/cli/build/tools/config/index.js:106:50)    at filterConfig (/~/example/node_modules/@react-native-community/cli/build/commands/config/config.js:13:20)    at Object.func (/~/example/node_modules/@react-native-community/cli/build/commands/config/config.js:27:32)    at Command.handleAction (/~/example/node_modules/@react-native-community/cli/build/index.js:186:23)    at Command.listener (/~/example/node_modules/commander/index.js:315:8)    at Command.emit (events.js:314:20)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
error Failed to build the app. Run CLI with --verbose flag for more details.
Error: Command failed: ./gradlew build -x lint
    at makeError (/~/example/node_modules/execa/index.js:174:9)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Diff:
```diff
diff --git a/example/react-native.config.js b/example/react-native.config.js
index 69684ba..cedf86c 100644
--- a/example/react-native.config.js
+++ b/example/react-native.config.js
@@ -7,8 +7,24 @@ if (process.argv.includes("--config=metro.config.macos.js")) {
     reactNativePath: "node_modules/react-native-windows",
   };
 } else {
+  const path = require("path");
+  const sourceDir = "android";
   module.exports = {
     project: {
+      android: {
+        sourceDir,
+        manifestPath: path.relative(
+          sourceDir,
+          path.join(
+            path.dirname(require.resolve("react-native-test-app/package.json")),
+            "android",
+            "app",
+            "src",
+            "main",
+            "AndroidManifest.xml"
+          )
+        ),
+      },
       ios: {
         project: "ios/ReactTestApp-Dummy.xcodeproj",
       },
```
